<a href="https://colab.research.google.com/github/CatalinaM15/Alura-Telecom-X---An-lisis-de-Evasi-n-de-Clientes/blob/main/TelecomX_LATAM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#📌 Extracción

## 📘 Diccionario de Datos — Telecom X

| Columna | Descripción |
|-------|-------------|
| **customerID** | Número de identificación único de cada cliente. |
| **Churn** | Indica si el cliente dejó o no la empresa. |
| **gender** | Género del cliente (Masculino / Femenino). |
| **SeniorCitizen** | Indica si el cliente tiene **65 años o más**. |
| **Partner** | Indica si el cliente tiene pareja. |
| **Dependents** | Indica si el cliente tiene dependientes. |
| **tenure** | Número de meses que el cliente ha permanecido con la empresa. |
| **PhoneService** | Indica si el cliente tiene servicio telefónico. |
| **MultipleLines** | Indica si el cliente tiene más de una línea telefónica. |
| **InternetService** | Tipo de proveedor de servicio de internet contratado. |
| **OnlineSecurity** | Indica si el cliente tiene servicio adicional de seguridad en línea. |
| **OnlineBackup** | Indica si el cliente tiene servicio adicional de respaldo en línea. |
| **DeviceProtection** | Indica si el cliente tiene protección adicional para su dispositivo. |
| **TechSupport** | Indica si el cliente tiene soporte técnico prioritario (menor tiempo de espera). |
| **StreamingTV** | Indica si el cliente tiene servicio de televisión por streaming. |
| **StreamingMovies** | Indica si el cliente tiene servicio de streaming de películas. |
| **Contract** | Tipo de contrato del cliente. |
| **PaperlessBilling** | Indica si el cliente prefiere recibir la factura de forma electrónica. |
| **PaymentMethod** | Método de pago utilizado por el cliente. |
| **Charges.Monthly** | Total de cargos mensuales por los servicios contratados. |
| **Charges.Total** | Total gastado por el cliente durante todo el tiempo que ha permanecido en la empresa. |

In [26]:

import pandas as pd
import requests
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import json

In [7]:
datos = requests.get('https://raw.githubusercontent.com/ingridcristh/challenge2-data-science-LATAM/main/TelecomX_Data.json')

In [12]:
resultado = json.loads(datos.text)
df = pd.DataFrame(resultado)
df.head()

In [13]:
df = pd.json_normalize(resultado)
df

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,No,No,13,Yes,No,DSL,...,No,No,Yes,No,No,One year,No,Mailed check,55.15,742.9
7263,9992-RRAMN,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,...,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.7
7264,9992-UJOEL,No,Male,0,No,No,2,Yes,No,DSL,...,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75
7265,9993-LHIEB,No,Male,0,Yes,Yes,67,Yes,No,DSL,...,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65
7266,9995-HOTOH,No,Male,0,Yes,Yes,63,No,No phone service,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.6

#🔧 Transformación

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7267 non-null   object
 1   Churn                      7267 non-null   object
 2   customer.gender            7267 non-null   object
 3   customer.SeniorCitizen     7267 non-null   int64
 4   customer.Partner           7267 non-null   object
 5   customer.Dependents        7267 non-null   object
 6   customer.tenure            7267 non-null   int64
 7   phone.PhoneService         7267 non-null   object
 8   phone.MultipleLines        7267 non-null   object
 9   internet.InternetService   7267 non-null   object
 10  internet.OnlineSecurity    7267 non-null   object
 11  internet.OnlineBackup      7267 non-null   object
 12  internet.DeviceProtection  7267 non-null   object
 13  internet.TechSupport       7267 non-null   object
 14  internet.StreamingTV       7267 non-null   object
 15  internet.StreamingMovies   7267 non-null   object
 16  account.Contract           7267 non-null   object
 17  account.PaperlessBilling   7267 non-null   object
 18  account.PaymentMethod      7267 non-null   object
 19  account.Charges.Monthly    7267 non-null   float64
 20  account.Charges.Total      7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

In [16]:
df.dtypes

customerID                    object
Churn                         object
customer.gender               object
customer.SeniorCitizen         int64
customer.Partner              object
customer.Dependents           object
customer.tenure                int64
phone.PhoneService            object
phone.MultipleLines           object
internet.InternetService      object
internet.OnlineSecurity       object
internet.OnlineBackup         object
internet.DeviceProtection     object
internet.TechSupport          object
internet.StreamingTV          object
internet.StreamingMovies      object
account.Contract              object
account.PaperlessBilling      object
account.PaymentMethod         object
account.Charges.Monthly      float64
account.Charges.Total         object
dtype: object

In [17]:
df.columns

Index(['customerID', 'Churn', 'customer.gender', 'customer.SeniorCitizen',
       'customer.Partner', 'customer.Dependents', 'customer.tenure',
       'phone.PhoneService', 'phone.MultipleLines', 'internet.InternetService',
       'internet.OnlineSecurity', 'internet.OnlineBackup',
       'internet.DeviceProtection', 'internet.TechSupport',
       'internet.StreamingTV', 'internet.StreamingMovies', 'account.Contract',
       'account.PaperlessBilling', 'account.PaymentMethod',
       'account.Charges.Monthly', 'account.Charges.Total'],
      dtype='object')

In [18]:
df["Churn"].value_counts()

Churn
No     5174
Yes    1869
        224
Name: count, dtype: int64

In [19]:
df.isnull().sum()

customerID                   0
Churn                        0
customer.gender              0
customer.SeniorCitizen       0
customer.Partner             0
customer.Dependents          0
customer.tenure              0
phone.PhoneService           0
phone.MultipleLines          0
internet.InternetService     0
internet.OnlineSecurity      0
internet.OnlineBackup        0
internet.DeviceProtection    0
internet.TechSupport         0
internet.StreamingTV         0
internet.StreamingMovies     0
account.Contract             0
account.PaperlessBilling     0
account.PaymentMethod        0
account.Charges.Monthly      0
account.Charges.Total        0
dtype: int64

In [21]:
df.duplicated().sum()

np.int64(0)

In [23]:
print("\nValores únicos en columnas categóricas:")
for col in df.select_dtypes(include="object").columns:
    print(f"\n{col}:")
    print(pd.unique(df[col]))

Valores únicos en columnas categóricas:

customerID:
['0002-ORFBO' '0003-MKNFE' '0004-TLHLJ' ... '9992-UJOEL' '9993-LHIEB'
 '9995-HOTOH']

Churn:
['No' 'Yes' '']

customer.gender:
['Female' 'Male']

customer.Partner:
['Yes' 'No']

customer.Dependents:
['Yes' 'No']

phone.PhoneService:
['Yes' 'No']

phone.MultipleLines:
['No' 'Yes' 'No phone service']

internet.InternetService:
['DSL' 'Fiber optic' 'No']

internet.OnlineSecurity:
['No' 'Yes' 'No internet service']

internet.OnlineBackup:
['Yes' 'No' 'No internet service']

internet.DeviceProtection:
['No' 'Yes' 'No internet service']

internet.TechSupport:
['Yes' 'No' 'No internet service']

internet.StreamingTV:
['Yes' 'No' 'No internet service']

internet.StreamingMovies:
['No' 'Yes' 'No internet service']

account.Contract:
['One year' 'Month-to-month' 'Two year']

account.PaperlessBilling:
['Yes' 'No']

account.PaymentMethod:
['Mailed check' 'Electronic check' 'Credit card (automatic)'
 'Bank transfer (automatic)']

account.Charges.Total:
['593.3' '542.4' '280.85' ... '742.9' '4627.65' '3707.6']

In [25]:
# Reemplazar strings vacíos por NaN
df["Churn"] = df["Churn"].replace("", np.nan)

# Revisar nuevamente valores nulos
print(df["Churn"].isnull().sum())

# Eliminar filas donde Churn es nulo
df = df.dropna(subset=["Churn"])

# Verificar resultado
print("\nDistribución de Churn después de limpieza:")
print(df["Churn"].value_counts())

224

Distribución de Churn después de limpieza:
Churn
no     5174
yes    1869
Name: count, dtype: int64